### ISSUE TITLE
Please, update your DOC. Not working with Node v14.17.6

### ISSUE THREAD

**Issue by sijjay** [artilleryio/artillery#1591]
Version info: 
```
perftest % node -v
v14.17.6

```

Running this command: 
```
<command>
```

I expected to see this happen:

*explanation*

Instead, this happened:

*explanation*

Files being used:
```
<relevant yaml/js/csv go here>
```

**Comment by sijjay** [comment]
```
perftest % artillery run config.yaml
(node:67752) [MODULE_NOT_FOUND] Error Plugin: artillery: Cannot find module 'node:util'
Require stack:
- /usr/local/lib/node_modules/artillery/core/lib/engine_http.js
- /usr/local/lib/node_modules/artillery/lib/cmds/probe.js
- /usr/local/lib/node_modules/artillery/node_modules/@oclif/config/lib/plugin.js
- /usr/local/lib/node_modules/artillery/node_modules/@oclif/config/lib/config.js
- /usr/local/lib/node_modules/artillery/node_modules/@oclif/config/lib/index.js
- /usr/local/lib/node_modules/artillery/node_modules/@oclif/command/lib/command.js
- /usr/local/lib/node_modules/artillery/node_modules/@oclif/command/lib/index.js
- /usr/local/lib/node_modules/artillery/bin/run
module: @oclif/config@1.18.3
task: toCached
plugin: artillery
root: /usr/local/lib/node_modules/artillery
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Scenario validation error: "scenarios" is required
```

**Comment by hassy** [comment]
thank you @sijjay, docs updated to ask for the latest LTS release of Node.js (v16 right now)
